Repository liferay/liferay-screens, pull requests merged in 2018-12, with the labels that each got.

#595 MOBILE-1048 Create DDMFormsScreenlet wrapper
  CHANGELOG.md
  android/library/src/main/java/com/liferay/mobile/screens/ddm/form/DDMFormListener.kt
  android/library/src/main/java/com/liferay/mobile/screens/ddm/form/DDMFormScreenlet.kt
  android/library/src/main/java/com/liferay/mobile/screens/thingscreenlet/screens/ThingScreenlet.kt
  android/library/src/main/java/com/liferay/mobile/screens/thingscreenlet/screens/ThingScreenletSavedState.kt
  android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormView.kt
  android/library/src/main/res/values/attrs.xml
  android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/DDMFormActivity.java
  android/samples/test-app/src/main/res/layout/ddm_form.xml
Labels: new feature

#593 #trivial MOBILE-1002 Fix local validation for StringField and NumberField
  android/build.gradle
  android/library/src/main/java/com/liferay/mobile/screens/ddl/NumberValidator.kt
  android/library/src/main/java/com/liferay/mobile/screens/ddl/StringValidator.kt
  android/library/src/main/java/com/liferay/mobile/screens/ddl/Validation.kt
  android/library/src/main/java/com/liferay/mobile/screens/ddl/model/Field.java
  android/library/src/main/java/com/liferay/mobile/screens/ddl/model/NumberField.java
  android/library/src/main/java/com/liferay/mobile/screens/ddl/model/StringField.java
  android/library/src/main/java/com/liferay/mobile/screens/util/AndroidUtil.kt
  android/library/src/main/java/com/liferay/mobile/screens/util/ValidationUtil.java
  android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddl/form/fields/BaseDDLFieldTextView.java
  android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormView.kt
  android/library/src/main/res/values/strings.xml
  android/library/src/test/java/com/liferay/mobile/screens/ddm/NumberValidatorTest.java
  android/library/src/test/java/com/liferay/mobile/screens/ddm/StringValidatorTest.java
  android/samples/test-app/src/main/res/values/strings.xml
  android/viewsets/lexicon/src/main/java/com/liferay/mobile/screens/viewsets/lexicon/ddl/form/fields/DDLFieldNumberView.java
  android/viewsets/lexicon/src/main/java/com/liferay/mobile/screens/viewsets/lexicon/ddl/form/fields/DDLFieldTextView.java
  android/viewsets/lexicon/src/main/java/com/liferay/mobile/screens/viewsets/lexicon/util/FormViewUtil.java
  android/viewsets/lexicon/src/main/res/layout/error_view.xml
  android/viewsets/lexicon/src/main/res/values/strings_lexicon.xml
Labels: bug

#590 #trivial MOBILE-966 DateField refactor
  android/library/src/main/java/com/liferay/mobile/screens/ddl/model/DateField.java
Labels: refactor
