Repository liferay/liferay-screens, pull requests merged in 2018-11, with the labels that each got.

#580 Support Swift 4.2
  .swift-version
  CHANGELOG.md
  LiferayScreens.podspec
  ios/Framework/Core/Auth/UserPortraitScreenlet/Interactors/DownloadUserPortraitInteractor.swift
  ios/Framework/Core/Auth/UserPortraitScreenlet/UploadUserPortraitLiferayConnector.swift
  ios/Framework/Core/Base/BaseConnectors/UploadFileConnector.swift
  ios/Framework/Core/Base/BaseListScreenlet/CollectionView/BaseListCollectionView.swift
  ios/Framework/Core/Base/BaseListScreenlet/TableView/BaseListTableView.swift
  ios/Framework/Core/Base/BaseScreenlet.swift
  ios/Framework/Core/Base/KeyboardManager.swift
  ios/Framework/Core/Base/MediaSelector.swift
  ios/Framework/Core/DDL/FormScreenlet/TableView/DDLFormTableView.swift
  ios/Framework/Core/Extensions/String+Screens.swift
  ios/Framework/Core/Extensions/UIButton+Screens.swift
  ios/Framework/Core/FileDisplay/ImageDisplayScreenlet.swift
  ios/Framework/Core/FileDisplay/ImageDisplayViewModel.swift
  ios/Framework/Core/Models/DDM/Fields/DDMField.swift
  ios/Framework/Core/Models/DDM/Fields/DDMFieldDocument.swift
  ios/Framework/Core/Offline/SyncManager.swift
  ios/Framework/LiferayScreens.xcodeproj/project.pbxproj
  ios/Framework/Podfile.lock
  ios/Framework/Tests/Unit/DDM/Fields/DDMFieldDocument_Tests.swift
  ios/Framework/Themes/Default/BlogsDisplay/BlogsEntryDisplayView_default.swift
  ios/Framework/Themes/Default/Comment/Display/CommentDisplayView_default.swift
  ios/Framework/Themes/Default/Comment/Display/CommentEditViewController_default.swift
  ios/Framework/Themes/Default/Comment/List/CommentListView_default.swift
  ios/Framework/Themes/Default/DDL/FormScreenlet/DDLFieldDocumentlibraryPresenterViewController_default.swift
  ios/Framework/Themes/Default/FileDisplay/ImageDisplayView_default.swift
  ios/Framework/Themes/Default/ImageGalleryScreenlet/ImageUploadDetailView_default.swift
  ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift.xcodeproj/project.pbxproj
  ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/AppDelegate.swift
  ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/ViewControllers/DDL/DDLListScreenletViewController.swift
  ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/ViewControllers/OfflineSyncViewController.swift
Labels: release

#578 LPS-86941 Support forms with ThingScreenlet
  CHANGELOG.md
  android/library/src/main/AndroidManifest.xml
  android/library/src/main/java/com/liferay/mobile/screens/ddm/form/model/FormInstance.kt
  android/library/src/main/java/com/liferay/mobile/screens/ddm/form/view/SuccessPageActivity.kt
  android/library/src/main/java/com/liferay/mobile/screens/thingscreenlet/delegates/ConverterDelegate.kt
  android/library/src/main/java/com/liferay/mobile/screens/thingscreenlet/screens/ThingScreenlet.kt
  android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/events/FormEvents.kt
  android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormContract.kt
  android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormInteractor.kt
  android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormPresenter.kt
  android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormView.kt
  android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/adapters/DDMPagerAdapter.kt
  android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/fields/DDMFieldCheckboxMultipleView.java
  android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/fields/DDMFieldGridRowView.kt
  android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/fields/DDMFieldGridView.kt
  android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/fields/DDMFieldRepeatableItemView.kt
  android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/fields/DDMFieldRepeatableView.kt
  android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/fields/ParagraphFieldTextView.java
  android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/fields/RepeatableActionListener.kt
  android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/pager/WrapContentViewPager.kt
  android/library/src/main/res/layout/ddm_form_default.xml
  android/library/src/main/res/layout/ddm_form_page_item.xml
  android/library/src/main/res/layout/ddm_form_success_page_default.xml
  android/library/src/main/res/layout/ddmfield_checkbox_multiple_default.xml
  android/library/src/main/res/layout/ddmfield_grid_default.xml
  android/library/src/main/res/layout/ddmfield_grid_row_default.xml
  android/library/src/main/res/layout/ddmfield_paragraph_default.xml
  android/library/src/main/res/layout/ddmfield_repeatable_default.xml
  android/library/src/main/res/layout/ddmfield_repeatable_item.xml
  android/library/src/main/res/values/ddmform_dimens.xml
  android/library/src/main/res/values/ddmform_strings.xml
  android/library/src/main/res/values/styles.xml
Labels: new feature

#582 LPS-87438 Create onPageRendered method on PdfDisplayView
  CHANGELOG.md
  android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/dlfile/display/PdfDisplayView.java
Labels: new feature

#583 LSR-1151 FormsScreenlet changes to adapt to API
  CHANGELOG.md
  android/library/src/main/java/com/liferay/mobile/screens/ddl/form/util/FormFieldKeys.kt
  android/library/src/main/java/com/liferay/mobile/screens/ddl/model/Field.java
  android/library/src/main/java/com/liferay/mobile/screens/ddl/model/SelectableOptionsField.java
Labels: refactor
