Repository liferay/liferay-screens, pull requests merged in 2018-10, with the labels that each got.

#564 LPS-86665 Fix isLiferay62 check on LiferayServerContext
  CHANGELOG.md
  android/library/src/main/java/com/liferay/mobile/screens/context/LiferayServerContext.java
Labels: bug

#563 LPS-86313 Update ThingScreenlet with Apio Consumer 0.0.8 changes and small fixes
  CHANGELOG.md
  android/build.gradle
  android/library/src/main/java/com/liferay/mobile/screens/thingscreenlet/model/Collection.kt
  android/library/src/main/java/com/liferay/mobile/screens/thingscreenlet/screens/ThingScreenlet.kt
  android/library/src/main/java/com/liferay/mobile/screens/thingscreenlet/screens/adapter/ThingAdapter.kt
  android/library/src/main/java/com/liferay/mobile/screens/thingscreenlet/screens/views/detail/BlogPostingDetailView.kt
  android/library/src/main/java/com/liferay/mobile/screens/util/AndroidUtil.kt
  android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/postings/activity/DetailActivity.kt
  android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/postings/activity/EditActivity.kt
  android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/postings/activity/ThingMainActivity.kt
  android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/postings/view/BlogPostingDetailCustom.kt
  android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/postings/view/CollectionDetailCustomView.kt
  android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/postings/view/PersonDetailCustom.kt
  android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/postings/view/PersonDetailSmall.kt
Labels: new feature

#575 #trivial LPS-86287 Update detekt version to RC9.2
  .gitignore
  .travis.yml
  android/build.gradle
  android/library/src/main/java/com/liferay/mobile/screens/ddl/NumberValidator.kt
  android/library/src/main/java/com/liferay/mobile/screens/ddl/StringValidator.kt
  android/library/src/main/java/com/liferay/mobile/screens/ddl/form/util/FormConstants.kt
  android/library/src/main/java/com/liferay/mobile/screens/ddl/form/util/FormFieldKeys.kt
  android/library/src/main/java/com/liferay/mobile/screens/ddl/model/SelectableOptionsField.java
  android/library/src/main/java/com/liferay/mobile/screens/ddl/model/StringField.java
  android/library/src/main/java/com/liferay/mobile/screens/thingscreenlet/screens/ThingScreenlet.kt
  android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddl/form/fields/DDLFieldTextView.kt
  android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/util/ThemeUtil.kt
  android/library/src/test/java/com/liferay/mobile/screens/ddl/model/DateFieldTest.java
  android/library/src/test/java/com/liferay/mobile/screens/ddl/model/RecordTest.java
  android/library/src/test/java/com/liferay/mobile/screens/ddl/model/SelectableOptionsFieldTest.java
  android/samples/test-app/proguard-rules.pro
  scripts/travis.sh
Labels: bug, refactor
